### ISSUE TITLE
TESTE

### ISSUE THREAD

**Issue by Luiz400122** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e4-proj-apdist-t4-controle_almoxarifado#2]

**Comment by thiago-alvaro** [comment]
Teste. Eliminada estar fora da configuração das Sprint, feita nova issue e adicionada à Sprint 1

**Comment by thiago-alvaro** [comment]
Teste.
Eliminada estar fora da configuração das Sprint, feita nova issue e adicionada à Sprint 1
